apiVersion: v1
kind: Secret
metadata:
  name: imt-server-secret
data:
  PGPASSWORD: a29sbGVjdGl2ZV4yMDIz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imt-server-env
data:
  TZ: "Asia/Bangkok"
  ConnectionStrings__SQL: "User ID=postgres;Host=54.169.242.40;Port=5432;Database=Imt_Dev;Pooling=true;Connection Lifetime=0;"
