apiVersion: v1
kind: Service
metadata:
    name: imt-server-service
spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
        app: imt-server
    type: ClusterIP